github: [thanhan92f1,Pho-Tue-SoftWare-Solutions-JSC]

custom:
  - https://github.com/Pho-Tue-SoftWare-Solutions-JSC
  - https://photuesoftware.com/
  - https://hitechcloud.vn/
  - https://my.hitechcloud.vn/
